blog/forms/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, ValidationError, SelectField
from wtforms.validators import DataRequired, Optional, Length
from flask_ckeditor import CKEditorField
# from blog.models import Category


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField()


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField()

blog/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, jsonify, Blueprint
from flask_login import current_user

from blog.models import User, Article, Notification
from blog.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # minus user self
    return jsonify(count=count)


@ajax_bp.route('/<int:article_id>/followers-count')
def collectors_count(article_id):
    article = Article.query.get_or_404(article_id)
    count = len(article.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:article_id>', methods=['POST'])
def collect(article_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    article = Article.query.get_or_404(article_id)
    if current_user.is_collecting(article):
        return jsonify(message='Already collected.'), 400

    current_user.collect(article)
    if current_user != article.author and article.author.receive_collect_notification:
        push_collect_notification(collector=current_user, article_id=article_id, receiver=article.author)
    return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:article_id>', methods=['POST'])
def uncollect(article_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    article = Article.query.get_or_404(article_id)
    if not current_user.is_collecting(article):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(article)
    return jsonify(message='Collect canceled.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')

blog/blueprints/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
import os

from flask import render_template, flash, redirect, url_for, current_app, \
    send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user, logout_user
from sqlalchemy.sql.expression import func

from blog.decorators import confirm_required, permission_required
from blog.extensions import db
from blog.forms.main import TagForm, CommentForm
# from blog.forms.user import ArticleForm
from blog.models import User, Article, Tag, Follow, Comment, Notification, Collect  #Category,
from blog.notifications import push_comment_notification, push_collect_notification
from blog.utils import redirect_back, flash_errors

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['BLOG_ARTICLE_PER_PAGE']
        pagination = Article.query \
            .join(Follow, Follow.followed_id == Article.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Article.timestamp.desc()) \
            .paginate(page, per_page)
        articles = pagination.items
    else:
        pagination = None
        articles = None
    tags = Tag.query.join(Tag.articles).group_by(Tag.id).order_by(func.count(Article.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, articles=articles, tags=tags)


# @main_bp.route('/explore')
# def explore():
#     articles = Article.query.order_by(func.random()).limit(12)
#     return render_template('main/explore.html', articles=articles)


@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about article, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'article')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_SEARCH_RESULT_PER_PAGE']
    # if category == 'user':
    #     pagination = User.query.whooshee_search(q).paginate(page, per_page)
    # elif category == 'tag':
    #     pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    # else:
    #     pagination = Article.query.whooshee_search(q).paginate(page, per_page)
    # results = pagination.items

    if category == 'user':
        middle_op = User.query.whooshee_search(q)
    elif category == 'tag':
        middle_op = Tag.query.whooshee_search(q)
    else:
        middle_op = Article.query.whooshee_search(q)
    results_all = middle_op.all()
    pagination = middle_op.paginate(page, per_page)
    results = pagination.items

    return render_template('main/search.html', q=q, results_all=results_all, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/article/<int:article_id>')  #methods=['GET', 'POST']
def show_article(article_id):
    article = Article.query.get_or_404(article_id)
    author = article.author
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(article).order_by(Comment.timestamp.desc()).paginate(
        page, per_page)
    last_articles = Article.query.with_parent(author).order_by(Article.timestamp.desc()).limit(10)
    last_comments = Comment.query.join(Article).join(User).filter(User.id == author.id) \
        .order_by(Comment.timestamp.desc()).limit(10)

    comments = pagination.items
    comment_form = CommentForm()
    tag_form = TagForm()
    return render_template('main/article.html', article=article, comment_form=comment_form, tag_form=tag_form,
                           pagination=pagination, comments=comments, last_articles=last_articles,
                           last_comments=last_comments)


@main_bp.route('/comment/<int:comment_id>')
def show_comment(comment_id):
    article = Comment.query.get_or_404(comment_id).article
    return redirect(url_for('.show_article', article_id=article.id) + '#comment-form')


@main_bp.route('/article/n/<int:article_id>')
def article_next(article_id):
    article = Article.query.get_or_404(article_id)
    article_n = Article.query.with_parent(article.author).filter(Article.id < article_id).order_by(Article.id.desc()).first()

    if article_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('.show_article', article_id=article_id))
    return redirect(url_for('.show_article', article_id=article_n.id))


@main_bp.route('/article/p/<int:article_id>')
def article_previous(article_id):
    article = Article.query.get_or_404(article_id)
    article_p = Article.query.with_parent(article.author).filter(Article.id > article_id).order_by(Article.id.asc()).first()

    if article_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('.show_article', article_id=article_id))
    return redirect(url_for('.show_article', article_id=article_p.id))


@main_bp.route('/set-comment/<int:article_id>', methods=['POST'])
@login_required
@confirm_required
def set_comment(article_id):
    article = Article.query.get_or_404(article_id)
    if current_user != article.author:
        abort(403)

    if article.can_comment:
        article.can_comment = False
        flash('Comment disabled', 'info')
    else:
        article.can_comment = True
        flash('Comment enabled.', 'info')
    db.session.commit()
    if request.args.get('next'):
        return redirect_back()
    return redirect(url_for('.show_article', article_id=article_id))


@main_bp.route('/article/<int:article_id>/comment/new', methods=['POST'])
@login_required
@confirm_required
@permission_required('COMMENT')
def new_comment(article_id):
    article = Article.query.get_or_404(article_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, article=article)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
            if comment.replied.author.receive_comment_notification:
                push_comment_notification(article_id=article.id, receiver=comment.replied.author)
        db.session.add(comment)
        db.session.commit()
        flash('Comment published.', 'success')

        if current_user != article.author and article.author.receive_comment_notification:
            push_comment_notification(article_id, receiver=article.author, page=page)

    flash_errors(form)
    return redirect(url_for('.show_article', article_id=article_id, page=page))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@confirm_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(
        url_for('.show_article', article_id=comment.article_id, reply=comment_id,
                author=comment.author.name) + '#comment-form')


@main_bp.route('/delete/comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.article.author \
            and not current_user.can('MODERATE'):
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'info')
    if request.args.get('next'):
        return redirect_back()
    return redirect(url_for('.show_article', article_id=comment.article_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_ARTICLE_PER_PAGE']
    order_rule = 'time'
    pagination = Article.query.with_parent(tag).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items

    if order == 'by_collects':
        articles.sort(key=lambda x: len(x.collectors), reverse=True)

blog/templates/main/_article_sidebar.html
{% from 'macros.html' import follow_area with context %}

<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=article.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=article.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', username=article.author.username) }}">{{ article.author.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ article.author.username }}</p>
                {{ follow_area(article.author) }}
            </div>
        </div>
    </div>
</div>
<div id="last_articles">
    <h3> last_articles </h3>
    <hr>
    <p>
        {% if last_articles %}
            {% for article in last_articles %}
                <a class="badge badge-light text-left"
                   href="{{ url_for('.show_article', article_id=article.id) }}" target="_blank">
                         {{ article.title }}</a>
            {% endfor %}
        {% endif %}
    </p>
</div>

<div id="last_comments">
    <h3> last_comments </h3>
    <hr>
        {% if last_comments %}
            {% for comment in last_comments %}
                <a class="badge badge-light text-left"
                   href="{{ url_for('.show_comment', comment_id=comment.id) }}" target="_blank">
                        <p>{{comment.article.title }}:{{comment.author.name}}:{{moment(comment.timestamp).fromNow(refresh=True)}}</p>
                        <p>{{comment.body|striptags|truncate}}</p>
                    </span>
                </a>
            {% endfor %}
        {% endif %}
</div>

blog/templates/main/_article_tips.html
{% from 'bootstrap/form.html' import  render_field %}

<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        <div id="tags">
            <p>
                {% if article.tags %}
                    {% for tag in article.tags %}
                        <a class="badge badge-light"
                           href="{{ url_for('.show_tag', tag_id=tag.id) }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
                {% if current_user == article.author %}
                    <a id="tag-btn" href="#!">
                        <small><span class="oi oi-pencil"></span> edit tag</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == article.author %}
            <!--如果没有js关于tag的hidden和show，<div id="tag-form"> 下面的无法显示，但是id改一下就可以，为什么-->
            <div id="tag-form">
                <form action="{{ url_for('.new_tag', article_id=article.id) }}" method="post">
                    {{ tag_form.csrf_token }}
                    {{ render_field(tag_form.tag) }}
                    <a class="btn btn-light btn-sm" id="cancel-tag">Cancel</a>
                    {{ render_field(tag_form.submit, class='btn btn-success btn-sm') }}
                </form>

                {% if article.tags %}
                    <hr>
                    {% for tag in article.tags %}
                    <a class="dead-link" href="#!"
                       data-href="{{ url_for('.delete_tag', article_id=article.id, tag_id=tag.id) }}"
                       data-toggle="modal" data-target="#confirm-delete" title="Delete tag">
                        <span class="badge badge-danger">
                            {{ tag.name }} <span class="oi oi-trash" aria-hidden="true"></span>
                        </span>
                    </a>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}
        {% if current_user.is_authenticated %}
            {% if current_user.is_collecting(article) %}
                <form class="inline" method="post"
                      action="{{ url_for('main.uncollect', article_id=article.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                        <span class="oi oi-x"></span> Uncollect
                    </button>
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('main.collect', article_id=article.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-primary btn-sm">
                        <span class="oi oi-star"></span> Collect
                    </button>
                </form>
            {% endif %}
        {% endif %}
        {% if article.collectors %}
            <a href="{{ url_for('main.show_collectors', article_id=article.id) }}">{{ article.collectors|length }}
                collectors</a>
        {% endif %}
    </div>
</div>

blog/templates/main/_comment.html
<div class="comments" id="comments">
    <h3>{{ article.comments|length }} Comments
        <small>
            <a href="{{ url_for('.show_article', article_id=article.id, page=pagination.pages or 1) }}#comment-form">latest</a>
        </small>
        {% if current_user == article.author %}
            <form class="inline" method="post" action="{{ url_for('.set_comment', article_id=article.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-xs btn-link float-right">
                    {% if article.can_comment %}Disable{% else %}Enable{% endif %} comment
                </button>
            </form>
        {% endif %}
    </h3>
    <hr>
    {% if comments %}
        {% for comment in comments %}
            <div class="comment">
                <div class="comment-thumbnail">
                    <a href="{{ url_for('user.index', username=comment.author.username) }}">
                        <img class="rounded img-fluid avatar-s profile-popover"
                             src="{{ url_for('main.get_avatar', filename=comment.author.avatar_s) }}">
                    </a>
                </div>
                <div class="comment-body">
                    <h6>
                        <a class="profile-popover"
                           href="{{ url_for('user.index', username=comment.author.username) }}">
                            {{ comment.author.name }}
                        </a>
                        {% if comment.author == article.author %}
                            <span class="badge badge-light">Author</span>
                        {% endif %}
                        <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ comment.timestamp }}"
                               data-delay="500">
                            {{ moment(comment.timestamp).fromNow(refresh=True) }}
                        </small>
                        {% if current_user.is_authenticated %}
                            <span class="float-right">
                            <span class="dropdown">
                                <button class="btn btn-sm btn-light" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                <span class="oi oi-ellipses"></span>
                                </button>
                                <span class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% if current_user != comment.author %}
                                    <a class="dropdown-item btn"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                    <span class="oi oi-comment-square"></span> Reply
                                </a>
                                {% endif %}
                                {% if current_user == comment.author or current_user == article.author or current_user.can('MODERATE') %}
                                    <a class="dropdown-item" data-toggle="modal" href="#!"
                                       data-href="{{ url_for('.delete_comment', comment_id=comment.id) }}"
                                       data-target="#confirm-delete">
                                    <span class="oi oi-trash" aria-hidden="true"></span> Delete
                                  </a>
                                {% endif %}
                                {% if current_user != comment.author %}
									<form class="inline" method="post"
										action="#">
									<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
									<button type="submit" class="dropdown-item">
										<span class="oi oi-warning" aria-hidden="true"></span> Report
									  </button>
									</form>
                                {% endif %}
                                </span>
                                </span>
                            </span>
                        {% endif %}
                    </h6>
                    <p>
					<!--下面的if不懂-->
                        {% if comment.replied %}
                            Reply
                            <a href="{{ url_for('user.index', username=comment.replied.author.username) }}">{{ comment.replied.author.name }}</a>:
                        {% endif %}
                        {{ comment.body }}
                    </p>
                </div>
            </div>
            <hr>
        {% endfor %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% else %}
        <p class="tip">No comments.</p>
    {% endif %}

    {% if article.can_comment %}
        {% if current_user.is_authenticated %}
            {% if current_user.can('COMMENT') %}
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">
                        Reply to {{ request.args.get('author') }}:
                        <a class="float-right" href="{{ url_for('.show_article', article_id=article.id) }}">Cancel</a>
                    </div>
                {% endif %}
                <div class="comment-form-area">
                    <div class="comment-form-thumbnail">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
                    </div>
                    <div class="comment-form" id="comment-form">
                        {{ render_form(comment_form, action=url_for('.new_comment', article_id=article.id, page=pagination.pages or 1,
                        reply=request.args.get('reply')),
                        extra_classes="text-right") }}
                    </div>
                </div>
            {% else %}
                <p class="tip">
                    No permission.
                </p>
            {% endif %}
        {% else %}
            <p class="tip">
                <a href="{{ url_for('auth.login') }}">Login</a>
                or
                <a href="{{ url_for('auth.register') }}">Register</a> to leave a comment.
            </p>
        {% endif %}
    {% else %}
        <p class="tip">
            Comment disabled.
        </p>
    {% endif %}
</div>

blog/templates/main/_sidebar.html
<!--
<div class="card bg-light mb-3 w-100 sidebar-nav">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=current_user.username) }}">
                <img class="rounded avatar-s" style="margin-left: 15px; position: absolute"
                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
            </a>
            <div class="sidebar-nav-name">
                <h6 class="card-title"><a
                        href="{{ url_for('user.index', username=current_user.username) }}">{{ current_user.name }}
                </a></h6>
                <p class="card-subtitle mb-2 text-muted">{{ current_user.username }}</p>
            </div>
        </div>
        <a class="card-link" href="{{ url_for('user.index', username=current_user.username) }}">
            <span class="oi oi-home"></span> My Articles
        </a><br>
        <a class="card-link" href="{{ url_for('user.show_collections', username=current_user.username) }}">
            <span class="oi oi-star"></span> My Collections
        </a>
    </div>
</div>
-->
<div class="card bg-light mb-3 w-100">
    <div class="card-header">Hot Tags</div>
    <div class="list-group">
        {% for tag in tags %}
            <a class="list-group-item" href="{{ url_for('.show_tag', tag_id=tag.id) }}">{{ tag.name }}
                <span class="badge badge-pill">{{ tag.articles|length }}</span>
            </a>
        {% endfor %}
    </div>
</div>

blog/templates/main/collectors.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}Collectors{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-default btn-sm" href="{{ url_for('main.show_article', article_id=article.id) }}">
                    <span class="oi oi-arrow-left" aria-hidden="true"></span> Return
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{{ article.collectors|length }} Collectors</h3>
            {% for collect in collects %}
                {{ user_card(user=collect.collector) }}
            {% endfor %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

blog/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import article_card with context %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
	<div class="col-md-8">
		{% if articles %}
			{% for article in articles %}
				{{ article_card(article) }} 
			{% endfor %}
		{% else %}
			<div class="tip text-center">
				<h3>No trends.</h3>
			</div>
		{% endif %}
	</div>
	<div class="col-md-3">
		{% include 'main/_sidebar.html' %}
	</div>
</div>
{% if articles %}
	{{ render_pagination(pagination, align='center') }}
{% endif %}

{% endblock %}

blog/templates/main/search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import article_card, user_card with context %}

{% block title %}Search: {{ q }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Search: {{ q }}</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                <a class="nav-item nav-link {% if category == 'article' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='article') }}">Article</a>
                <a class="nav-item nav-link {% if category == 'user' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='user') }}">User</a>
                <a class="nav-item nav-link {% if category == 'tag' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='tag') }}">Tag</a>
            </div>
        </div>
        <div class="col-md-9">
            {% if results %}
                <h5>{{ results_all|length }} results</h5>
                {% for item in results %}
                    {% if category == 'article' %}
                        {{ article_card(item) }}
                    {% elif category == 'user' %}
                        {{ user_card(item) }}
                    {% else %}
                        <a class="badge badge-light" href="{{ url_for('.show_tag', tag_id=item.id) }}">
                            {{ item.name }} {{ item.articles|length }}
                        </a>
                    {% endif %}
                {% endfor %}

            {% else %}
                <h5 class="tip">No results.</h5>
            {% endif %}
        </div>
    </div>
    {% if results %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='right') }}
        </div>
    {% endif %}
{% endblock %}