blog/blueprints/admin.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, flash, Blueprint, request, current_app
from flask_login import login_required

from blog.decorators import admin_required, permission_required
from blog.extensions import db
from blog.forms.admin import EditProfileAdminForm
from blog.models import Role, User, Tag, Article, Comment
from blog.utils import redirect_back

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    user_count = User.query.count()
    locked_user_count = User.query.filter_by(locked=True).count()
    blocked_user_count = User.query.filter_by(active=False).count()
    article_count = Article.query.count()
    reported_articles_count = Article.query.filter(Article.flag > 0).count()
    tag_count = Tag.query.count()
    comment_count = Comment.query.count()
    reported_comments_count = Comment.query.filter(Comment.flag > 0).count()
    return render_template('admin/index.html', user_count=user_count, article_count=article_count,
                           tag_count=tag_count, comment_count=comment_count, locked_user_count=locked_user_count,
                           blocked_user_count=blocked_user_count, reported_comments_count=reported_comments_count,
                           reported_articles_count=reported_articles_count)


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.name = form.name.data
        role = Role.query.get(form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.bio = form.bio.data
        user.website = form.website.data
        user.confirmed = form.confirmed.data
        user.active = form.active.data
        user.location = form.location.data
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect_back()
    form.name.data = user.name
    form.role.data = user.role_id
    form.bio.data = user.bio
    form.website.data = user.website
    form.location.data = user.location
    form.username.data = user.username
    form.email.data = user.email
    form.confirmed.data = user.confirmed
    form.active.data = user.active
    return render_template('admin/edit_profile.html', form=form, user=user)


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    user = User.query.get_or_404(user_id)
    if user.role.name in ['Administrator', 'Moderator']:
        flash('Permission denied.', 'warning')
    else:
        user.block()
        flash('Account blocked.', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unblock()
    flash('Block canceled.', 'info')
    return redirect_back()


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    user = User.query.get_or_404(user_id)
    if user.role.name in ['Administrator', 'Moderator']:
        flash('Permission denied.', 'warning')
    else:
        user.lock()
        flash('Account locked.', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unlock()
    flash('Lock canceled.', 'info')
    return redirect_back()


@admin_bp.route('/delete/tag/<int:tag_id>', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def delete_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash('Tag deleted.', 'info')
    return redirect_back()


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'locked', 'blocked', 'administrator', 'moderator'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_USER_PER_PAGE']
    administrator = Role.query.filter_by(name='Administrator').first()
    moderator = Role.query.filter_by(name='Moderator').first()

    if filter_rule == 'locked':
        filtered_users = User.query.filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = User.query.filter_by(active=False)
    elif filter_rule == 'administrator':
        filtered_users = User.query.filter_by(role=administrator)
    elif filter_rule == 'moderator':
        filtered_users = User.query.filter_by(role=moderator)
    else:
        filtered_users = User.query

    pagination = filtered_users.order_by(User.member_since.desc()).paginate(page, per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_PHOTO_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = Article.query.order_by(Article.timestamp.desc()).paginate(page, per_page)
        order_rule = 'time'
    else:
        pagination = Article.query.order_by(Article.flag.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('admin/manage_article.html', pagination=pagination, articles=articles, order_rule=order_rule)


@admin_bp.route('/manage/tag')
@login_required
@permission_required('MODERATE')
def manage_tag():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_TAG_PER_PAGE']
    pagination = Tag.query.order_by(Tag.id.desc()).paginate(page, per_page)
    tags = pagination.items
    return render_template('admin/manage_tag.html', pagination=pagination, tags=tags)


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page)
        order_rule = 'time'
    else:
        pagination = Comment.query.order_by(Comment.flag.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, comments=comments, order_rule=order_rule)

blog/blueprints/user.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, flash, redirect, url_for, current_app, request, Blueprint, abort
from flask_login import login_required, current_user, fresh_login_required, logout_user

from blog.decorators import confirm_required, permission_required
from blog.emails import send_change_email_email
from blog.extensions import db, avatars
from blog.forms.user import EditProfileForm, UploadAvatarForm, CropAvatarForm, ChangeEmailForm, ArticleForm,\
    ChangePasswordForm, NotificationSettingForm, PrivacySettingForm, DeleteAccountForm          # CategoryForm
from blog.models import User, Article, Collect, Comment  # Category
from blog.notifications import push_follow_notification
from blog.settings import Operations
from blog.utils import generate_token, validate_token, redirect_back, flash_errors

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    '''
    if user == current_user and user.locked:
        flash('Your account is locked.', 'danger')

    if user == current_user and not user.active:
        logout_user()
    '''
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_ARTICLE_PER_PAGE']
    pagination = Article.query.filter(Article.author_id == user.id).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, articles=articles)


# @user_bp.route('/<username>/category/<int:category_id>')
# def show_category(username, category_id):
#     user = User.query.filter_by(username=username).first_or_404()
#     '''
#     if user == current_user and user.locked:
#         flash('Your account is locked.', 'danger')
#
#     if user == current_user and not user.active:
#         logout_user()
#     '''
#     category = user.categories.query.filer_by(id=category_id).first_or_404()   #类似User.unfollow方法
#     page = request.args.get('page', 1, type=int)
#     per_page = current_app.config['BLOG_Article_PER_PAGE']
#     pagination = Article.query.filter(Article.author_id == user.id).filter(Article.category_id == category.id).
#     order_by(Article.timestamp.desc()).paginate(page, per_page)
#     # pagination = Article.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
#     articles = pagination.items
#     return render_template('user/category.html', user=user, category=category, pagination=pagination,
#     articles=articles)
#
#
# @user_bp.route('/<username>/category/manage')
# @login_required
# @confirm_required
# def manage_category(username):
#     user = User.query.filter_by(username=username).first_or_404()
#     if user != current_user:
#         abort(403)
#     return render_template('user/manage_category.html')
#
#
# @user_bp.route('/<username>/category/new', methods=['GET', 'POST'])
# @login_required
# @confirm_required
# def new_category(username):
#     user = User.query.filter_by(username=username).first_or_404()
#     if user != current_user:
#         abort(403)
#     form = CategoryForm()
#     if form.validate_on_submit():
#         name = form.name.data
#         '''
#         category = Category.query.filter_by(name=name).first()
#         if category is None:
#             category = Category(name=name)
#             db.session.add(category)
#             db.session.commit()
#         if category not in user.categories:
#             user.categories.append(category)
#             db.session.commit()
#         '''
#         # 除了category.id=1,其他的category的user都只有一个
#         category = Category(name=name)
#         user.categories.append(category)
#         db.session.add(category)
#         db.session.commit()
#
#         flash('Category created.', 'success')
#         return redirect(url_for('.manage_category'))
#     return render_template('user/new_category.html', form=form)
#
#
# @user_bp.route('/<username>/category/<int:category_id>/edit', methods=['GET', 'POST'])
# @login_required
# @confirm_required
# def edit_category(username, category_id):
#     user = User.query.filter_by(username=username).first_or_404()
#     if user != current_user:
#         abort(403)
#     form = CategoryForm()
#     category = Category.query.get_or_404(category_id)
#     if category.id == 1:
#         flash('You can not edit the default category.', 'warning')
#         return redirect(url_for('user.index'))
#     if form.validate_on_submit():
#         '''
#         user.categories.remove(category)
#         db.session.commit()
#         if not category.users:
#             db.session.delete(category)
#             db.session.commit()
#         '''
#         category.name = form.name.data
#         db.session.commit()
#         flash('Category updated.', 'success')
#         return redirect(url_for('.manage_category'))
#
#     form.name.data = category.name
#     return render_template('user/edit_category.html', form=form)


# @user_bp.route('/<username>/category/<int:category_id>/delete', methods=['POST'])
# @login_required
# @confirm_required
# def delete_category(username, category_id):
#     user = User.query.filter_by(username=username).first_or_404()
#     if user != current_user:
#         abort(403)
#     category = Category.query.get_or_404(category_id)
#     if category.id == 1:
#         flash('You can not delete the default category.', 'warning')
#         return redirect(url_for('blog.index'))
#     category.delete()
#     flash('Category deleted.', 'success')
#     return redirect(url_for('.manage_category'))


@user_bp.route('/<username>/article/manage')
@login_required
@confirm_required
def manage_article(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        abort(403)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_ARTICLE_PER_PAGE']
    pagination = Article.query.filter(Article.author_id == user.id).order_by(Article.timestamp.desc()).paginate(page, per_page)
    articles = pagination.items
    return render_template('user/manage_article.html', page=page, pagination=pagination, articles=articles)


@user_bp.route('/<username>/comment/manage')
@login_required
@confirm_required
def manage_comment(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        abort(403)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.filter(Comment.author_id == user.id).order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('user/manage_comment.html', page=page, comments=comments, pagination=pagination)


@user_bp.route('/<username>/article/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_article(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        abort(403)

    form = ArticleForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        # category = Category.query.get(form.category.data)  #form.category.data是id？
        article = Article(title=title, body=body, author=current_user._get_current_object())

        # same with:
        # category_id = form.category.data
        # post = Post(title=title, body=body, category_id=category_id,author_id=current_user.id)
        db.session.add(article)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('main.show_article', article_id=article.id))
    return render_template('user/new_article.html', form=form)


@user_bp.route('/<username>/article/<int:article_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_article(username, article_id):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        abort(403)

    form = ArticleForm()
    article = Article.query.get_or_404(article_id)
    if form.validate_on_submit():
        article.title = form.title.data
        article.body = form.body.data
        # article.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Article updated.', 'success')
        return redirect(url_for('main.show_article', article_id=article.id))
    form.title.data = article.title
    form.body.data = article.body
    # form.category.data = article.category_id
    return render_template('user/edit_article.html', form=form)


@user_bp.route('/<username>/article/<int:article_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_article(username, article_id):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        abort(403)

    article = Article.query.get_or_404(article_id)
    db.session.delete(article)
    db.session.commit()
    flash('Article deleted.', 'success')
    return redirect_back()


@user_bp.route('/<username>/collections')
def show_collections(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_ARTICLE_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user, pagination=pagination, collects=collects)



@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
@confirm_required
@permission_required('FOLLOW')
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()

blog/templates/user/_header.html
{% from 'macros.html' import follow_area with context %}
{% from 'bootstrap/nav.html' import render_nav_item %}


<div class="row">
    <div class="col-md-3">
        <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}"
           title="Change avatar">
            <img class="img-fluid rounded" src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
        </a>
    </div>
    <div class="col-md-9">
        <h1>{{ user.name }}
            <small class="text-muted">{{ user.username }}</small>
        </h1>
        {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
        <p>
            {% if user.website %}
                <span class="oi oi-link-intact"></span>
                <a href="{{ user.website }}" target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            {% if user.location %}
                <span class="oi oi-map-marker"></span>
                <a href="https://www.google.com/maps?q={{ user.location }}"
                   target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            <span class="oi oi-calendar"></span>
            Joined {{ moment(user.member_since).format('LL') }}
        </p>
        <div>
            {% if current_user != user %}
                {% if current_user.can('MODERATE') %}
                    {% if user.locked %}
                        <form class="inline" action="{{ url_for('admin.unlock_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-secondary btn-sm" value="Unlock">
                        </form>
                    {% else %}
                        <form class="inline" action="{{ url_for('admin.lock_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-warning btn-sm" value="Lock">
                        </form>
                    {% endif %}
                    {% if user.active %}
                        <form class="inline" action="{{ url_for('admin.block_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-warning btn-sm" value="Block">
                        </form>
                    {% else %}
                        <form class="inline" action="{{ url_for('admin.unblock_user', user_id=user.id) }}"
                              method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-secondary btn-sm" value="Unblock">
                        </form>
                    {% endif %}
                    <a class="btn btn-light btn-sm" href="mailto:{{ user.email }}">Email</a>
                {% endif %}

                {% if current_user.is_admin %}
                    <a class="btn btn-warning btn-sm" href="{{ url_for('admin.edit_profile_admin', user_id=user.id) }}">Edit
                        profile</a>
                {% endif %}
            {% endif %}
            <div class="float-right">
                {{ follow_area(user) }}
                {% if current_user.is_authenticated and user == current_user %}
                    <a class="btn btn-outline-primary btn-sm" href="{{ url_for('.edit_profile') }}">Edit profile</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="user-nav">
    <ul class="nav nav-tabs">
        {{ render_nav_item('user.index', 'Article', user.articles|length, username=user.username) }}
        {{ render_nav_item('user.show_collections', 'Collections', user.collections|length, username=user.username) }}
        {{ render_nav_item('user.show_following', 'Following', user.following.count() - 1, username=user.username) }}
        {{ render_nav_item('user.show_followers', 'Follower', user.followers.count() - 1, username=user.username) }}
        {% if current_user.is_authenticated and user == current_user %}
        {{ render_nav_item('user.manage_article', 'Manage', username=user.username) }}
        {% endif %}
    </ul>
</div>

blog/templates/user/collections.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import article_card with context%}

{% block title %}{{ user.name }}'s collection{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if user.public_collections or current_user == user %}
                {% if collects %}
                    {% for collect in collects %}
                        {{ article_card(collect.collected) }}
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>No collection.</h3>
                    </div>
                {% endif %}
            {% else %}
                <div class="tip">
                    <h3>This user's collections was private.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

blog/templates/user/edit_article.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Article{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Edit Article</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
    
{% endblock %}

blog/templates/user/edit_link.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Link{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Edit Link</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

blog/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s followers{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.follower != user %}
                        {{ user_card(user=follow.follower) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No followers.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

blog/templates/user/following.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s following{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.followed != user %}
                        {{ user_card(user=follow.followed) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No followings.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

blog/templates/user/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import article_card with context %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if articles %}
                {% for article in articles %}
                    {{ article_card(article) }}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No articles.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if articles %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

blog/templates/user/manage_article.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Manage Article{% endblock %}

{% block content %}
{% include 'user/manage_header.html' %}
<div class="page-header">
    <h1>Article
        <small class="text-muted">{{ pagination.total }}</small>
        <span class="float-right"><a class="btn btn-primary btn-sm"
                                     href="{{ url_for('user.new_article',username=current_user.username) }}">New Article</a></span>
    </h1>
</div>
{% if articles %}
<table class="table table-striped">
    <thead>
    <tr>
        <th>No.</th>
        <th>Title</th>
        <th>Date</th>
        <th>Comments</th>
        <th>Words</th>
        <th>Actions</th>
    </tr>
    </thead>
    {% for article in articles %}
    <tr>
        <td>{{ loop.index + ((page - 1) * config.BLOG_MANAGE_ARTICLE_PER_PAGE) }}</td>
        <td><a href="{{ url_for('main.show_article', article_id=article.id) }}">{{ article.title }}</a></td>
        <td>{{ moment(article.timestamp).format('LL') }}</td>
        <td><a href="{{ url_for('main.show_article', article_id=article.id) }}#comments">{{ article.comments|length }}</a></td>
        <td>{{ article.body|length }}</td>
        <td>
            <form class="inline" method="post"
                  action="{{ url_for('main.set_comment', article_id=article.id, next=request.full_path) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button type="submit" class="btn btn-warning btn-sm">
                    {% if article.can_comment %}Disable{% else %}Enable{% endif %} Comment
                </button>
            </form>
            <a class="btn btn-info btn-sm" href="{{ url_for('.edit_article', username=current_user.username,article_id=article.id) }}">Edit</a>
            <form class="inline" method="post"
                  action="{{ url_for('.delete_article', article_id=article.id, username=current_user.username, next=request.full_path) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
<div class="page-footer">{{ render_pagination(pagination) }}</div>
{% else %}
<div class="tip"><h5>No articles.</h5></div>
{% endif %}
{% endblock %}

blog/templates/user/manage_header.html
<ul class="nav nav-tabs">
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
       aria-haspopup="true"
       aria-expanded="false">
        New <span class="caret"></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ url_for('user.new_article',username=current_user.username)}}">Article</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
       aria-haspopup="true"
       aria-expanded="false">
        Manage <span class="caret"></span>
        {% if unread_comments %}
            <span class="badge badge-success">new</span>
        {% endif %}
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ url_for('user.manage_article', username=current_user.username)}}">Article</a>
        <a class="dropdown-item" href="{{ url_for('user.manage_comment', username=current_user.username)}}">Comment</a>
    </div>
</li>
</ul>

blog/templates/user/new_article.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}New Article{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>New Article</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

blog/templates/user/settings.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Settings{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Settings</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}